### ISSUE TITLE
(Fix) remove all occurences of `wizard.poa.network` link from the code

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/e2e-test-token-wizard#1]
For example, here: https://github.com/poanetwork/e2e-test-token-wizard/blob/master/pages/InvestPage.js#L15

Let's define URL of wizard everywhere from `startURL` parameter https://github.com/poanetwork/e2e-test-token-wizard/blob/master/config.json#L2

**Comment by dennis00010011b** [comment]
Done
