### ISSUE TITLE
(Feature) add path to output directory to config file

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/e2e-test-token-wizard#13]
**Problem**: there are multiple folders are created in the root path.

![screen shot 2018-02-15 at 14 29 21](https://user-images.githubusercontent.com/4341812/36254587-ab0d09ea-125c-11e8-8079-86621704dad6.png)

**Solution**: create one folder for output files and add an ability to manage path from the config file. In this folder `./results...` folders will be added and `./artifacts` folder. 

Also, I am curious what is the difference between screenshots in `./artifacts` folder and in `./results...` folders. Do we need `./artifacts` folder at all?

**Comment by dennis00010011b** [comment]
Fixed
https://github.com/poanetwork/e2e-test-token-wizard
