### ISSUE TITLE
(Feature) add networkID to config

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/e2e-test-token-wizard#2]
Let's create a network provider URL in the config to simplify switching between networks. Or, maybe, it is a better idea to store `networkID` in the config and choose provider depending on `networkID`. The list of network IDs can be taken from [here](https://ethereum.stackexchange.com/questions/17051/how-to-select-a-network-id-or-is-there-a-list-of-network-ids). Also, we need to get networkID from config for URLs like this: https://github.com/poanetwork/e2e-test-token-wizard/blob/70ceccc5db2301220bfbcd5c02a60f197c20f79b/pages/InvestPage.js#L15

**Comment by dennis00010011b** [comment]
Now *networkID* can be set in scenario file 
 https://github.com/poanetwork/e2e-test-token-wizard/blob/master/T2RyWy.json

Possible values:
0,1,2 - Main Etherium network;
 3 - Ropsten;
 4 - Rinkeby;
 42 - Kovan;
 77 - Sokol;
 99 - Poa core;
 8545 - localhost 8545
