### ISSUE TITLE
(Bug) NoSuchElementError: no such element: Unable to locate element

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/e2e-test-token-wizard#8]
`NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app-content"]/div/div[4]/div/div/div[2]/div[1]/div/div/div[1]/div[1]"}` with all configs are default from the repo 

[error.log](https://github.com/poanetwork/e2e-test-token-wizard/files/1706851/error.log)

![screen shot 2018-02-08 at 14 36 58](https://user-images.githubusercontent.com/4341812/35971131-df53c0ce-0cdd-11e8-9b64-82342cb2fd02.png)

**Comment by dennis00010011b** [comment]
I can't reproduce it. Looks like wrong private key was entered and next page wasn't loaded

**Comment by vbaranov** [comment]
Problem is disappeared with release 1.0.38
